import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "To-do list app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-stone-100">{children}</body>
    </html>
  );
}
